### ISSUE TITLE
Special Characters such as + caused build failure

### ISSUE THREAD

**Issue by iNoles** [grab/cocoapods-pod-merge#8]
Here is an example of "UITableView+FDTemplateLayoutCell" in https://github.com/forkingdog/UITableView-FDTemplateLayoutCell

**Comment by biocross** [comment]
Ah good catch! Looks the `.modulemap` file cannot accept special characters like `+` in the framework name. I have fixed this in master. Thank you for reporting.

**Comment by biocross** [comment]
@iNoles This has been fixed in [Release 0.0.3](https://github.com/grab/cocoapods-pod-merge/releases/tag/0.0.3)
