### ISSUE TITLE
YYTextSelectionView.h file not found error when merging YYKit

### ISSUE THREAD

**Issue by c137Choi** [grab/cocoapods-pod-merge#9]
![image](https://user-images.githubusercontent.com/13805289/68278867-319df880-00ad-11ea-9cd1-a0ee88672014.png)
Sames that the 'has_dependencies!' flag won't help in this circumstance, 'cause the YYTextSelectionView is part of the framework.

**Comment by biocross** [comment]
Hi @OriTheElf,

I checked this pod, and unfortunately it has a typo in the `YYTextEffectWindow.h` file. The plugin can replace imports matching the exact name of the pod, which is `YYText`, but not `YYtext`; this operation is case sensitive. 

I'm not sure why this compiles fine independently, but this pod needs to fix the import to `#import <YYText/YYTextSelectionView.h>` for the has_dependencies! flag to work.
